import { createApp, defineComponent } from 'vue'
import App from './app.vue'
// const app = createApp({
//   template: `<router-view />`
// })
import { createRouter, createWebHistory } from 'vue-router'
// import routes generated by Voie
import routes from 'virtual:generated-pages'
import store from 'virtual:generated-store'

import { createStore } from 'vuex'
// console.log('App: ', App)
const app = createApp(App)
app.use(createStore(store))

console.log('store.code: ', store)
const router = createRouter({
  history: createWebHistory(),
  routes
})
app.use(router)
app.mount('#app')
