import { getXx } from '@/utils/db'
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
// import routes generated by Voie
import routes from 'virtual:generated-pages'
import { store } from '@normo/store'
import App from './app.vue'
// const app = createApp({
//   template: '<router-view />'
// })

import { createStore } from 'vuex'
const app = createApp(App)
// console.log('App: ', App)
app.use(store)

console.log('store.code: ', store)
const router = createRouter({
  history: createWebHistory(),
  routes
})
app.use(router)
app.mount('#app')

console.log('xxxxxxxxxxxx')
