import { getXx } from '@/utils/db.ts'
import { createApp, defineComponent } from '@normo/vue'
import App from './app.vue'
// const app = createApp({
//   template: `<router-view />`
// })
import { createRouter, createWebHistory } from '@normo/vue-router'
// import routes generated by Voie
import routes from 'virtual:generated-pages'
import { store } from '@normo/store'
console.log('getXx: ', getXx())

// import { createStore } from 'vuex'
// console.log('App: ', App)
const app = createApp(App)
app.use(store)

console.log('store.code: ', store)
const router = createRouter({
  history: createWebHistory(),
  routes
})
app.use(router)
app.mount('#app')

console.log('xxxxxxxxxxxx')
